In [1]:
import pandas as pd
import numpy as np
import pyarrow as pa
import  pyarrow.parquet as pq

In [14]:
dfItens = pd.read_csv("../../Microdados_enem_2019/DADOS/ITENS_PROVA_2019.csv", sep=';',encoding='iso-8859-1')

In [27]:
arrayGab = {"CN":[], "MT":[], "CH":[], "LC":[]}

lstRows = []

for subject in arrayGab.keys():
    dfSubject = dfItens[dfItens["SG_AREA"]==subject]

    blueCode = dfSubject[dfSubject["TX_COR"]=="Azul"]["CO_PROVA"].unique()[0]
    dfCodes = dfSubject[dfSubject["CO_PROVA"]==blueCode][["CO_ITEM"]]

    for code in dfSubject['CO_PROVA'].unique():

        dfSubjectFiltered = dfSubject[dfSubject["CO_PROVA"]==code][["CO_ITEM", "CO_POSICAO", "TP_LINGUA"]]

        if subject == "LC":
            for i in range(2):
                dfSubjectFiltered[]
                dfSubjectFiltered["CO_POSICAO"] = dfSubjectFiltered["CO_POSICAO"] - np.min(dfSubjectFiltered["CO_POSICAO"])

        dfCodes = dfCodes.merge(dfSubjectFiltered, on="CO_ITEM", how="left", suffixes=(None, "_"+str(code)))

    dfCodes.rename(columns= {"CO_POSICAO":"CO_POSICAO_" + str(blueCode)}, inplace=True) 
    arrayResp[subject] = dfCodes

arrayResp["MT"].loc[0,"CO_POSICAO_522"] = 15

In [28]:
arrayResp["MT"]

CO_ITEM  CO_POSICAO_515  CO_POSICAO_516  CO_POSICAO_517  CO_POSICAO_518  \
0    117635               0               3               6              15   
1      9779               1               4               7              16   
2    111608               2               5               8              17   
3    111696               3              27              31              41   
4     63187               4               8              12               0   
5    117612               5               9              13               1   
6     63808               6              10              14               2   
7     54448               7              11              15               3   
8     86432               8              12              16               4   
9     23065               9              13              17               5   
10   117798              10              14              18               6   
11    30740              11              15              19               7   
12    30436              12              16              20               8   
13   117725              13              17              21               9   
14    84409              14              18              22              10   
15    28434              15              19              23              11   
16   117607              16              20              24              12   
17    30570              17              21              25              13   
18    84374              18              22              26              14   
19    83754              19              23              27              37   
20    39708              20              24              28              38   
21   117950              21              25              29              39   
22   117845              22              26              30              40   
23   117726              23              28              34              18   
24     8368              24              29              35              19   
25    13303              25              30              36              20   
26    14324              26              31              37              21   
27    18002              27              32              38              22   
28    42803              28              33              39              23   
29   117743              29              34              40              24   
30    10360              30              35              41              25   
31    31184              31              36              42              26   
32     8401              32              37              43              27   
33   117818              33              38              44              28   
34   117783              34               0               9              29   
35    83792              35               1              10              30   
36     8442              36               2              11              31   
37    89634              37              40              32              42   
38    78445              38              41              33              43   
39    17642              39              42               2              34   
40   117767              40              43               3              35   
41    83955              41              44               4              36   
42   111593              42              39               5              44   
43   111518              43               6               0              32   
44    83994              44               7               1              33   

    CO_POSICAO_522  CO_POSICAO_526  CO_POSICAO_555  CO_POSICAO_556  \
0             15.0              15             NaN             NaN   
1             16.0              16             NaN             NaN   
2             17.0              17             NaN             NaN   
3             41.0              41             NaN             NaN   
4              0.0 

In [29]:
arr = dfItens[dfItens["CO_PROVA"]==522]['CO_ITEM'].unique()
arr2 = dfItens[dfItens["CO_PROVA"]==515]['CO_ITEM'].unique()

In [30]:
np.setdiff1d(arr, arr2)

array([96479], dtype=int64)

In [31]:
dfItens["SG_AREA"].unique()

array(['LC', 'CH', 'CN', 'MT'], dtype=object)

In [32]:
dfSub = {"CN":[], "MT":[], "CH":[], "LC":[]}

for sub in dfSub.keys():
    dfSub[sub] = pd.read_parquet(f'../../Datasets/BySubject/{sub}_2019_SAOPAULO.parquet')
    print(sub)
    print(dfSub[sub][f"CO_PROVA_{sub}"].unique())


CN
[505. 504. 503. 506. 523. 519.]
MT
[518. 516. 515. 517. 526. 522.]
CH
[509. 510. 507. 508. 524. 520.]
LC
[514. 513. 511. 512. 525. 521.]


In [33]:
dfHead = dfSub["LC"].head(10)
dfHead

NU_INSCRICAO  LC1  LC2  LC3  LC4  LC5  LC6  LC7  LC8  LC9  ...  LC38  LC39  \
0  190001592266  1.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  ...   1.0   1.0   
1  190001595667  0.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0  1.0  ...   1.0   0.0   
2  190001595676  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...   0.0   0.0   
3  190001595684  0.0  1.0  0.0  1.0  1.0  0.0  1.0  1.0  0.0  ...   0.0   0.0   
4  190001595691  1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  ...   1.0   1.0   
5  190001595698  0.0  1.0  1.0  1.0  0.0  0.0  0.0  1.0  1.0  ...   1.0   0.0   
6  190001595700  0.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0  0.0  ...   1.0   1.0   
7  190001595703  1.0  1.0  1.0  1.0  1.0  1.0  0.0  1.0  1.0  ...   0.0   0.0   
8  190001595705  1.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0  ...   1.0   0.0   
9  190001595714  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  ...   0.0   0.0   

   LC40  LC41  LC42  LC43  LC44  LC45  NU_NOTA_LC  CO_PROVA_LC  
0   0.0   1.0   0.0   0.0   1.0   0.0       502.5        514.0  
1   0.0   1.0   0.0   0.0   0.0   0.0       518.2        513.0  
2   1.0   1.0   0.0   1.0   0.0   0.0       600.0        511.0  
3   0.0   0.0   0.0   1.0   0.0   0.0       517.3        511.0  
4   0.0   1.0   1.0   1.0   0.0   0.0       569.6        514.0  
5   1.0   0.0   0.0   1.0   0.0   0.0       510.7        514.0  
6   0.0   1.0   1.0   1.0   0.0   0.0       531.3        514.0  
7   1.0   1.0   1.0   0.0   1.0   1.0       639.9        512.0  
8   1.0   1.0   0.0   1.0   0.0   0.0       566.0        512.0  
9   0.0   1.0   1.0   0.0   0.0   0.0       537.4        512.0  

[10 rows x 48 columns]

In [34]:
for i, column in enumerate(dfHead.columns[1:46]):
    dfHead.loc[:, column] = str(i)+"_"

dfHead

C:\Users\Gustavo Castro\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexing.py:1817: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)


NU_INSCRICAO LC1 LC2 LC3 LC4 LC5 LC6 LC7 LC8 LC9  ... LC38 LC39 LC40 LC41  \
0  190001592266  0_  1_  2_  3_  4_  5_  6_  7_  8_  ...  37_  38_  39_  40_   
1  190001595667  0_  1_  2_  3_  4_  5_  6_  7_  8_  ...  37_  38_  39_  40_   
2  190001595676  0_  1_  2_  3_  4_  5_  6_  7_  8_  ...  37_  38_  39_  40_   
3  190001595684  0_  1_  2_  3_  4_  5_  6_  7_  8_  ...  37_  38_  39_  40_   
4  190001595691  0_  1_  2_  3_  4_  5_  6_  7_  8_  ...  37_  38_  39_  40_   
5  190001595698  0_  1_  2_  3_  4_  5_  6_  7_  8_  ...  37_  38_  39_  40_   
6  190001595700  0_  1_  2_  3_  4_  5_  6_  7_  8_  ...  37_  38_  39_  40_   
7  190001595703  0_  1_  2_  3_  4_  5_  6_  7_  8_  ...  37_  38_  39_  40_   
8  190001595705  0_  1_  2_  3_  4_  5_  6_  7_  8_  ...  37_  38_  39_  40_   
9  190001595714  0_  1_  2_  3_  4_  5_  6_  7_  8_  ...  37_  38_  39_  40_   

  LC42 LC43 LC44 LC45 NU_NOTA_LC CO_PROVA_LC  
0  41_  42_  43_  44_      502.5       514.0  
1  41_  42_  43_  44_      518.2       513.0  
2  41_  42_  43_  44_      600.0       511.0  
3  41_  42_  43_  44_      517.3       511.0  
4  41_  42_  43_  44_      569.6       514.0  
5  41_  42_  43_  44_      510.7       514.0  
6  41_  42_  43_  44_      531.3       514.0  
7  41_  42_  43_  44_      639.9       512.0  
8  41_  42_  43_  44_      566.0       512.0  
9  41_  42_  43_  44_      537.4       512.0  

[10 rows x 48 columns]

In [35]:
for index, row in dfHead.iterrows():
    codigo = int(row["CO_PROVA_LC"])
    arrayPos = np.array(arrayResp["LC"][f"CO_POSICAO_{codigo}"]) + 1 
    arrayPos = np.insert(arrayPos, 0 , 0)
    arrayPos = np.insert(arrayPos, 46 , 46)
    arrayPos = np.insert(arrayPos, 47 , 47)

    rowCopy = dfHead.iloc[index, arrayPos]

    dfHead.iloc[index, :] = rowCopy

ValueError: Must have equal len keys and value when setting with an iterable